name: yt_dlp_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  crypto: ^3.0.6
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  collection: ^1.19.1
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
